on:
  push:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo deploying

  uat:
    name: uat
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: UAT
        run: echo uat
  hml:
    name: hml
    runs-on: ubuntu-latest
    needs: uat
    steps:
      - name: HML
        run: echo hml

  prod: 
    name: prod
    runs-on: ubuntu-latest
    needs: hml
    steps:
      - name: PROD
        run: echo prod